with-expecter: true
all: false

packages:
  github.com/Arturikou/urlshortener/internal/handlers:
    config:
      dir: "mocks"
      outpkg: "mocks"
      filename: "{{.InterfaceName | snakecase}}_mock.go"
    interfaces:
      URLService: {}
  github.com/Arturikou/urlshortener/internal/service/shortener:
    config:
      dir: "mocks"
      outpkg: "mocks"
      filename: "{{.InterfaceName | snakecase}}_mock.go"
    interfaces:
      Repository: {}
  github.com/Arturikou/urlshortener/internal/storage/pinger:
    config:
      dir: "mocks"
      outpkg: "mocks"
      filename: "{{.InterfaceName | snakecase}}_mock.go"
    interfaces:
      Pinger: {}