package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const marker = "generate:reset"

func main() {
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := walkPackages(root); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func walkPackages(root string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		base := filepath.Base(path)
		if strings.HasPrefix(base, ".") || base == "vendor" || base == "testdata" {
			return filepath.SkipDir
		}
		return processDir(path)
	})
}

type fieldInfo struct {
	name     string
	typeExpr ast.Expr
}

type structInfo struct {
	name   string
	fields []fieldInfo
}

func processDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}

	fset := token.NewFileSet()
	pkgStructs := map[string][]structInfo{}
	pkgSeen := map[string]string{}

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() ||
			!strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") ||
			name == "reset.gen.go" {
			continue
		}

		path := filepath.Join(dir, name)
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			continue
		}

		pkgName := file.Name.Name
		pkgSeen[pkgName] = pkgName

		structs := collectStructs(file)
		pkgStructs[pkgName] = append(pkgStructs[pkgName], structs...)
	}

	for pkgName, structs := range pkgStructs {
		_ = pkgSeen[pkgName]
		if len(structs) == 0 {
			continue
		}
		if err := writeResetFile(dir, pkgName, structs); err != nil {
			return fmt.Errorf("write %s/reset.gen.go: %w", dir, err)
		}
	}
	return nil
}

func collectStructs(file *ast.File) []structInfo {
	var result []structInfo
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		if !hasMarker(genDecl.Doc) {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			var fields []fieldInfo
			for _, field := range st.Fields.List {
				for _, fname := range field.Names {
					fields = append(fields, fieldInfo{
						name:     fname.Name,
						typeExpr: field.Type,
					})
				}
			}
			result = append(result, structInfo{name: ts.Name.Name, fields: fields})
		}
	}
	return result
}

func hasMarker(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == marker {
			return true
		}
	}
	return false
}

func writeResetFile(dir, pkgName string, structs []structInfo) error {
	var buf bytes.Buffer
	fmt.Fprint(&buf, "// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, s := range structs {
		writeResetMethod(&buf, s)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		src = buf.Bytes()
		fmt.Fprintf(os.Stderr, "format error in %s: %v\n", dir, err)
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0o644)
}

func writeResetMethod(buf *bytes.Buffer, s structInfo) {
	fmt.Fprintf(buf, "func (v *%s) Reset() {\n", s.name)
	fmt.Fprint(buf, "\tif v == nil {\n\t\treturn\n\t}\n")
	for _, f := range s.fields {
		writeFieldReset(buf, "v."+f.name, f.typeExpr, 1)
	}
	fmt.Fprint(buf, "}\n\n")
}

func writeFieldReset(buf *bytes.Buffer, expr string, t ast.Expr, depth int) {
	tab := strings.Repeat("\t", depth)

	switch typ := t.(type) {
	case *ast.Ident:
		switch typ.Name {
		case "string":
			fmt.Fprintf(buf, "%s%s = \"\"\n", tab, expr)
		case "bool":
			fmt.Fprintf(buf, "%s%s = false\n", tab, expr)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"byte", "rune", "float32", "float64":
			fmt.Fprintf(buf, "%s%s = 0\n", tab, expr)
		default:
			fmt.Fprintf(buf, "%sif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", tab, expr)
			fmt.Fprintf(buf, "%s\tresetter.Reset()\n", tab)
			fmt.Fprintf(buf, "%s}\n", tab)
		}

	case *ast.StarExpr:
		fmt.Fprintf(buf, "%sif %s != nil {\n", tab, expr)
		writeFieldReset(buf, "(*"+expr+")", typ.X, depth+1)
		fmt.Fprintf(buf, "%s}\n", tab)

	case *ast.ArrayType:
		if typ.Len == nil {
			fmt.Fprintf(buf, "%s%s = %s[:0]\n", tab, expr, expr)
		}

	case *ast.MapType:
		fmt.Fprintf(buf, "%sclear(%s)\n", tab, expr)

	case *ast.SelectorExpr:
		fmt.Fprintf(buf, "%sif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", tab, expr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n", tab)
		fmt.Fprintf(buf, "%s}\n", tab)
	}
}
