// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Arturikou/urlshortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetURLByAlias provides a mock function with given fields: ctx, alias
func (_m *MockRepository) GetURLByAlias(ctx context.Context, alias string) (string, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetByAlias")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetURLByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAlias'
type MockRepository_GetURLByAlias_Call struct {
	*mock.Call
}

// GetURLByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockRepository_Expecter) GetURLByAlias(ctx interface{}, alias interface{}) *MockRepository_GetURLByAlias_Call {
	return &MockRepository_GetURLByAlias_Call{Call: _e.mock.On("GetByAlias", ctx, alias)}
}

func (_c *MockRepository_GetURLByAlias_Call) Run(run func(ctx context.Context, alias string)) *MockRepository_GetURLByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetURLByAlias_Call) Return(_a0 string, _a1 error) *MockRepository_GetURLByAlias_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetURLByAlias_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRepository_GetURLByAlias_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOrGetAlias provides a mock function with given fields: ctx, data
func (_m *MockRepository) InsertOrGetAlias(ctx context.Context, data models.URLData) (models.UpsertResult, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrGetAlias")
	}

	var r0 models.UpsertResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.URLData) (models.UpsertResult, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.URLData) models.UpsertResult); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(models.UpsertResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.URLData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_InsertOrGetAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrGetAlias'
type MockRepository_InsertOrGetAlias_Call struct {
	*mock.Call
}

// InsertOrGetAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.URLData
func (_e *MockRepository_Expecter) InsertOrGetAlias(ctx interface{}, data interface{}) *MockRepository_InsertOrGetAlias_Call {
	return &MockRepository_InsertOrGetAlias_Call{Call: _e.mock.On("InsertOrGetAlias", ctx, data)}
}

func (_c *MockRepository_InsertOrGetAlias_Call) Run(run func(ctx context.Context, data models.URLData)) *MockRepository_InsertOrGetAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.URLData))
	})
	return _c
}

func (_c *MockRepository_InsertOrGetAlias_Call) Return(_a0 models.UpsertResult, _a1 error) *MockRepository_InsertOrGetAlias_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_InsertOrGetAlias_Call) RunAndReturn(run func(context.Context, models.URLData) (models.UpsertResult, error)) *MockRepository_InsertOrGetAlias_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: ctx, data
func (_m *MockRepository) SaveBatch(ctx context.Context, data []*models.ShortenBatch) ([]*models.ShortenBatch, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 []*models.ShortenBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ShortenBatch) ([]*models.ShortenBatch, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ShortenBatch) []*models.ShortenBatch); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ShortenBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.ShortenBatch) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type MockRepository_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - data []*models.ShortenBatch
func (_e *MockRepository_Expecter) SaveBatch(ctx interface{}, data interface{}) *MockRepository_SaveBatch_Call {
	return &MockRepository_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, data)}
}

func (_c *MockRepository_SaveBatch_Call) Run(run func(ctx context.Context, data []*models.ShortenBatch)) *MockRepository_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.ShortenBatch))
	})
	return _c
}

func (_c *MockRepository_SaveBatch_Call) Return(_a0 []*models.ShortenBatch, _a1 error) *MockRepository_SaveBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_SaveBatch_Call) RunAndReturn(run func(context.Context, []*models.ShortenBatch) ([]*models.ShortenBatch, error)) *MockRepository_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
