// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Arturikou/urlshortener/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockURLRepo is an autogenerated mock type for the URLRepo type
type MockURLRepo struct {
	mock.Mock
}

type MockURLRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepo) EXPECT() *MockURLRepo_Expecter {
	return &MockURLRepo_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: ctx, data
func (_m *MockURLRepo) AddURL(ctx context.Context, data models.URLData) (int64, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.URLData) (int64, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.URLData) int64); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.URLData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepo_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type MockURLRepo_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.URLData
func (_e *MockURLRepo_Expecter) AddURL(ctx interface{}, data interface{}) *MockURLRepo_AddURL_Call {
	return &MockURLRepo_AddURL_Call{Call: _e.mock.On("AddURL", ctx, data)}
}

func (_c *MockURLRepo_AddURL_Call) Run(run func(ctx context.Context, data models.URLData)) *MockURLRepo_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.URLData))
	})
	return _c
}

func (_c *MockURLRepo_AddURL_Call) Return(_a0 int64, _a1 error) *MockURLRepo_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepo_AddURL_Call) RunAndReturn(run func(context.Context, models.URLData) (int64, error)) *MockURLRepo_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// CountUrls provides a mock function with given fields: ctx
func (_m *MockURLRepo) CountUrls(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountUrls")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepo_CountUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUrls'
type MockURLRepo_CountUrls_Call struct {
	*mock.Call
}

// CountUrls is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockURLRepo_Expecter) CountUrls(ctx interface{}) *MockURLRepo_CountUrls_Call {
	return &MockURLRepo_CountUrls_Call{Call: _e.mock.On("CountUrls", ctx)}
}

func (_c *MockURLRepo_CountUrls_Call) Run(run func(ctx context.Context)) *MockURLRepo_CountUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockURLRepo_CountUrls_Call) Return(_a0 int64, _a1 error) *MockURLRepo_CountUrls_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepo_CountUrls_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockURLRepo_CountUrls_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteURLs provides a mock function with given fields: ctx, userID, aliases
func (_m *MockURLRepo) DeleteURLs(ctx context.Context, userID uuid.UUID, aliases []string) error {
	ret := _m.Called(ctx, userID, aliases)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) error); ok {
		r0 = rf(ctx, userID, aliases)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepo_DeleteURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLs'
type MockURLRepo_DeleteURLs_Call struct {
	*mock.Call
}

// DeleteURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - aliases []string
func (_e *MockURLRepo_Expecter) DeleteURLs(ctx interface{}, userID interface{}, aliases interface{}) *MockURLRepo_DeleteURLs_Call {
	return &MockURLRepo_DeleteURLs_Call{Call: _e.mock.On("DeleteURLs", ctx, userID, aliases)}
}

func (_c *MockURLRepo_DeleteURLs_Call) Run(run func(ctx context.Context, userID uuid.UUID, aliases []string)) *MockURLRepo_DeleteURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockURLRepo_DeleteURLs_Call) Return(_a0 error) *MockURLRepo_DeleteURLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepo_DeleteURLs_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) error) *MockURLRepo_DeleteURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAlias provides a mock function with given fields: ctx, alias
func (_m *MockURLRepo) GetByAlias(ctx context.Context, alias string) (models.URLRecord, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetByAlias")
	}

	var r0 models.URLRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.URLRecord, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.URLRecord); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(models.URLRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepo_GetByAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAlias'
type MockURLRepo_GetByAlias_Call struct {
	*mock.Call
}

// GetByAlias is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLRepo_Expecter) GetByAlias(ctx interface{}, alias interface{}) *MockURLRepo_GetByAlias_Call {
	return &MockURLRepo_GetByAlias_Call{Call: _e.mock.On("GetByAlias", ctx, alias)}
}

func (_c *MockURLRepo_GetByAlias_Call) Run(run func(ctx context.Context, alias string)) *MockURLRepo_GetByAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepo_GetByAlias_Call) Return(_a0 models.URLRecord, _a1 error) *MockURLRepo_GetByAlias_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepo_GetByAlias_Call) RunAndReturn(run func(context.Context, string) (models.URLRecord, error)) *MockURLRepo_GetByAlias_Call {
	_c.Call.Return(run)
	return _c
}

// GetByURL provides a mock function with given fields: ctx, url
func (_m *MockURLRepo) GetByURL(ctx context.Context, url string) (models.URLRecord, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetByURL")
	}

	var r0 models.URLRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.URLRecord, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.URLRecord); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(models.URLRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepo_GetByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByURL'
type MockURLRepo_GetByURL_Call struct {
	*mock.Call
}

// GetByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockURLRepo_Expecter) GetByURL(ctx interface{}, url interface{}) *MockURLRepo_GetByURL_Call {
	return &MockURLRepo_GetByURL_Call{Call: _e.mock.On("GetByURL", ctx, url)}
}

func (_c *MockURLRepo_GetByURL_Call) Run(run func(ctx context.Context, url string)) *MockURLRepo_GetByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepo_GetByURL_Call) Return(_a0 models.URLRecord, _a1 error) *MockURLRepo_GetByURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepo_GetByURL_Call) RunAndReturn(run func(context.Context, string) (models.URLRecord, error)) *MockURLRepo_GetByURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: ctx, data
func (_m *MockURLRepo) SaveBatch(ctx context.Context, data []models.ShortenBatch) ([]models.ShortenBatch, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 []models.ShortenBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.ShortenBatch) ([]models.ShortenBatch, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.ShortenBatch) []models.ShortenBatch); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ShortenBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.ShortenBatch) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepo_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type MockURLRepo_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - data []models.ShortenBatch
func (_e *MockURLRepo_Expecter) SaveBatch(ctx interface{}, data interface{}) *MockURLRepo_SaveBatch_Call {
	return &MockURLRepo_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, data)}
}

func (_c *MockURLRepo_SaveBatch_Call) Run(run func(ctx context.Context, data []models.ShortenBatch)) *MockURLRepo_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.ShortenBatch))
	})
	return _c
}

func (_c *MockURLRepo_SaveBatch_Call) Return(_a0 []models.ShortenBatch, _a1 error) *MockURLRepo_SaveBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepo_SaveBatch_Call) RunAndReturn(run func(context.Context, []models.ShortenBatch) ([]models.ShortenBatch, error)) *MockURLRepo_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLRepo creates a new instance of MockURLRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepo {
	mock := &MockURLRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
