// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Arturikou/urlshortener/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserURLRepo is an autogenerated mock type for the UserURLRepo type
type MockUserURLRepo struct {
	mock.Mock
}

type MockUserURLRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserURLRepo) EXPECT() *MockUserURLRepo_Expecter {
	return &MockUserURLRepo_Expecter{mock: &_m.Mock}
}

// AddUserURL provides a mock function with given fields: ctx, userID, urlID
func (_m *MockUserURLRepo) AddUserURL(ctx context.Context, userID uuid.UUID, urlID int64) error {
	ret := _m.Called(ctx, userID, urlID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = rf(ctx, userID, urlID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserURLRepo_AddUserURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserURL'
type MockUserURLRepo_AddUserURL_Call struct {
	*mock.Call
}

// AddUserURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - urlID int64
func (_e *MockUserURLRepo_Expecter) AddUserURL(ctx interface{}, userID interface{}, urlID interface{}) *MockUserURLRepo_AddUserURL_Call {
	return &MockUserURLRepo_AddUserURL_Call{Call: _e.mock.On("AddUserURL", ctx, userID, urlID)}
}

func (_c *MockUserURLRepo_AddUserURL_Call) Run(run func(ctx context.Context, userID uuid.UUID, urlID int64)) *MockUserURLRepo_AddUserURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockUserURLRepo_AddUserURL_Call) Return(_a0 error) *MockUserURLRepo_AddUserURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserURLRepo_AddUserURL_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) error) *MockUserURLRepo_AddUserURL_Call {
	_c.Call.Return(run)
	return _c
}

// CountUsers provides a mock function with given fields: ctx
func (_m *MockUserURLRepo) CountUsers(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountUsers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserURLRepo_CountUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUsers'
type MockUserURLRepo_CountUsers_Call struct {
	*mock.Call
}

// CountUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserURLRepo_Expecter) CountUsers(ctx interface{}) *MockUserURLRepo_CountUsers_Call {
	return &MockUserURLRepo_CountUsers_Call{Call: _e.mock.On("CountUsers", ctx)}
}

func (_c *MockUserURLRepo_CountUsers_Call) Run(run func(ctx context.Context)) *MockUserURLRepo_CountUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserURLRepo_CountUsers_Call) Return(_a0 int64, _a1 error) *MockUserURLRepo_CountUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserURLRepo_CountUsers_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockUserURLRepo_CountUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: ctx, userID
func (_m *MockUserURLRepo) GetUserURLs(ctx context.Context, userID uuid.UUID) ([]models.UserUrls, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []models.UserUrls
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserUrls, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserUrls); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserUrls)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserURLRepo_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockUserURLRepo_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserURLRepo_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *MockUserURLRepo_GetUserURLs_Call {
	return &MockUserURLRepo_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *MockUserURLRepo_GetUserURLs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserURLRepo_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserURLRepo_GetUserURLs_Call) Return(_a0 []models.UserUrls, _a1 error) *MockUserURLRepo_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserURLRepo_GetUserURLs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserUrls, error)) *MockUserURLRepo_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserURLRepo creates a new instance of MockUserURLRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserURLRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserURLRepo {
	mock := &MockUserURLRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
