// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockDeleteEnqueuer is an autogenerated mock type for the DeleteEnqueuer type
type MockDeleteEnqueuer struct {
	mock.Mock
}

type MockDeleteEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteEnqueuer) EXPECT() *MockDeleteEnqueuer_Expecter {
	return &MockDeleteEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueDelete provides a mock function with given fields: userID, aliases
func (_m *MockDeleteEnqueuer) EnqueueDelete(userID uuid.UUID, aliases []string) {
	_m.Called(userID, aliases)
}

// MockDeleteEnqueuer_EnqueueDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDelete'
type MockDeleteEnqueuer_EnqueueDelete_Call struct {
	*mock.Call
}

// EnqueueDelete is a helper method to define mock.On call
//   - userID uuid.UUID
//   - aliases []string
func (_e *MockDeleteEnqueuer_Expecter) EnqueueDelete(userID interface{}, aliases interface{}) *MockDeleteEnqueuer_EnqueueDelete_Call {
	return &MockDeleteEnqueuer_EnqueueDelete_Call{Call: _e.mock.On("EnqueueDelete", userID, aliases)}
}

func (_c *MockDeleteEnqueuer_EnqueueDelete_Call) Run(run func(userID uuid.UUID, aliases []string)) *MockDeleteEnqueuer_EnqueueDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].([]string))
	})
	return _c
}

func (_c *MockDeleteEnqueuer_EnqueueDelete_Call) Return() *MockDeleteEnqueuer_EnqueueDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeleteEnqueuer_EnqueueDelete_Call) RunAndReturn(run func(uuid.UUID, []string)) *MockDeleteEnqueuer_EnqueueDelete_Call {
	_c.Run(run)
	return _c
}

// NewMockDeleteEnqueuer creates a new instance of MockDeleteEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteEnqueuer {
	mock := &MockDeleteEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
