// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shortener "github.com/Arturikou/urlshortener/internal/service/shortener"
)

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: ctx, url
func (_m *MockURLService) AddURL(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type MockURLService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockURLService_Expecter) AddURL(ctx interface{}, url interface{}) *MockURLService_AddURL_Call {
	return &MockURLService_AddURL_Call{Call: _e.mock.On("AddURL", ctx, url)}
}

func (_c *MockURLService_AddURL_Call) Run(run func(ctx context.Context, url string)) *MockURLService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_AddURL_Call) Return(_a0 string, _a1 error) *MockURLService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_AddURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockURLService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// AddURLs provides a mock function with given fields: ctx, shortenBatch
func (_m *MockURLService) AddURLs(ctx context.Context, shortenBatch []*shortener.ShortenBatch) ([]shortener.ShortenBatch, error) {
	ret := _m.Called(ctx, shortenBatch)

	if len(ret) == 0 {
		panic("no return value specified for AddURLs")
	}

	var r0 []shortener.ShortenBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*shortener.ShortenBatch) ([]shortener.ShortenBatch, error)); ok {
		return rf(ctx, shortenBatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*shortener.ShortenBatch) []shortener.ShortenBatch); ok {
		r0 = rf(ctx, shortenBatch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]shortener.ShortenBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*shortener.ShortenBatch) error); ok {
		r1 = rf(ctx, shortenBatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_AddURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURLs'
type MockURLService_AddURLs_Call struct {
	*mock.Call
}

// AddURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenBatch []*shortener.ShortenBatch
func (_e *MockURLService_Expecter) AddURLs(ctx interface{}, shortenBatch interface{}) *MockURLService_AddURLs_Call {
	return &MockURLService_AddURLs_Call{Call: _e.mock.On("AddURLs", ctx, shortenBatch)}
}

func (_c *MockURLService_AddURLs_Call) Run(run func(ctx context.Context, shortenBatch []*shortener.ShortenBatch)) *MockURLService_AddURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*shortener.ShortenBatch))
	})
	return _c
}

func (_c *MockURLService_AddURLs_Call) Return(_a0 []shortener.ShortenBatch, _a1 error) *MockURLService_AddURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_AddURLs_Call) RunAndReturn(run func(context.Context, []*shortener.ShortenBatch) ([]shortener.ShortenBatch, error)) *MockURLService_AddURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: ctx, alias
func (_m *MockURLService) GetURL(ctx context.Context, alias string) (string, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockURLService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLService_Expecter) GetURL(ctx interface{}, alias interface{}) *MockURLService_GetURL_Call {
	return &MockURLService_GetURL_Call{Call: _e.mock.On("GetURL", ctx, alias)}
}

func (_c *MockURLService_GetURL_Call) Run(run func(ctx context.Context, alias string)) *MockURLService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_GetURL_Call) Return(_a0 string, _a1 error) *MockURLService_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockURLService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
