// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: url
func (_m *MockURLService) AddURL(url string) (string, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type MockURLService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - url string
func (_e *MockURLService_Expecter) AddURL(url interface{}) *MockURLService_AddURL_Call {
	return &MockURLService_AddURL_Call{Call: _e.mock.On("AddURL", url)}
}

func (_c *MockURLService_AddURL_Call) Run(run func(url string)) *MockURLService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLService_AddURL_Call) Return(_a0 string, _a1 error) *MockURLService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_AddURL_Call) RunAndReturn(run func(string) (string, error)) *MockURLService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: id
func (_m *MockURLService) GetURL(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockURLService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - id string
func (_e *MockURLService_Expecter) GetURL(id interface{}) *MockURLService_GetURL_Call {
	return &MockURLService_GetURL_Call{Call: _e.mock.On("GetURL", id)}
}

func (_c *MockURLService_GetURL_Call) Run(run func(id string)) *MockURLService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLService_GetURL_Call) Return(_a0 string, _a1 error) *MockURLService_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_GetURL_Call) RunAndReturn(run func(string) (string, error)) *MockURLService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
