// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Arturikou/urlshortener/internal/models"

	shortener "github.com/Arturikou/urlshortener/internal/service/shortener"

	uuid "github.com/google/uuid"
)

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// AddURL provides a mock function with given fields: ctx, originalURL
func (_m *MockURLService) AddURL(ctx context.Context, originalURL string) (shortener.AddURLResult, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for AddURL")
	}

	var r0 shortener.AddURLResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (shortener.AddURLResult, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) shortener.AddURLResult); ok {
		r0 = rf(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(shortener.AddURLResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_AddURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURL'
type MockURLService_AddURL_Call struct {
	*mock.Call
}

// AddURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockURLService_Expecter) AddURL(ctx interface{}, originalURL interface{}) *MockURLService_AddURL_Call {
	return &MockURLService_AddURL_Call{Call: _e.mock.On("AddURL", ctx, originalURL)}
}

func (_c *MockURLService_AddURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockURLService_AddURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_AddURL_Call) Return(_a0 shortener.AddURLResult, _a1 error) *MockURLService_AddURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_AddURL_Call) RunAndReturn(run func(context.Context, string) (shortener.AddURLResult, error)) *MockURLService_AddURL_Call {
	_c.Call.Return(run)
	return _c
}

// AddURLs provides a mock function with given fields: ctx, shortenBatch
func (_m *MockURLService) AddURLs(ctx context.Context, shortenBatch []*models.ShortenBatch) ([]models.ShortenBatch, error) {
	ret := _m.Called(ctx, shortenBatch)

	if len(ret) == 0 {
		panic("no return value specified for AddURLs")
	}

	var r0 []models.ShortenBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ShortenBatch) ([]models.ShortenBatch, error)); ok {
		return rf(ctx, shortenBatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.ShortenBatch) []models.ShortenBatch); ok {
		r0 = rf(ctx, shortenBatch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ShortenBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.ShortenBatch) error); ok {
		r1 = rf(ctx, shortenBatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_AddURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddURLs'
type MockURLService_AddURLs_Call struct {
	*mock.Call
}

// AddURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenBatch []*models.ShortenBatch
func (_e *MockURLService_Expecter) AddURLs(ctx interface{}, shortenBatch interface{}) *MockURLService_AddURLs_Call {
	return &MockURLService_AddURLs_Call{Call: _e.mock.On("AddURLs", ctx, shortenBatch)}
}

func (_c *MockURLService_AddURLs_Call) Run(run func(ctx context.Context, shortenBatch []*models.ShortenBatch)) *MockURLService_AddURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.ShortenBatch))
	})
	return _c
}

func (_c *MockURLService_AddURLs_Call) Return(_a0 []models.ShortenBatch, _a1 error) *MockURLService_AddURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_AddURLs_Call) RunAndReturn(run func(context.Context, []*models.ShortenBatch) ([]models.ShortenBatch, error)) *MockURLService_AddURLs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserURLs provides a mock function with given fields: ctx, aliases, userID
func (_m *MockURLService) DeleteUserURLs(ctx context.Context, aliases []string, userID uuid.UUID) error {
	ret := _m.Called(ctx, aliases, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, uuid.UUID) error); ok {
		r0 = rf(ctx, aliases, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLService_DeleteUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserURLs'
type MockURLService_DeleteUserURLs_Call struct {
	*mock.Call
}

// DeleteUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - aliases []string
//   - userID uuid.UUID
func (_e *MockURLService_Expecter) DeleteUserURLs(ctx interface{}, aliases interface{}, userID interface{}) *MockURLService_DeleteUserURLs_Call {
	return &MockURLService_DeleteUserURLs_Call{Call: _e.mock.On("DeleteUserURLs", ctx, aliases, userID)}
}

func (_c *MockURLService_DeleteUserURLs_Call) Run(run func(ctx context.Context, aliases []string, userID uuid.UUID)) *MockURLService_DeleteUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockURLService_DeleteUserURLs_Call) Return(_a0 error) *MockURLService_DeleteUserURLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLService_DeleteUserURLs_Call) RunAndReturn(run func(context.Context, []string, uuid.UUID) error) *MockURLService_DeleteUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: ctx, alias
func (_m *MockURLService) GetURL(ctx context.Context, alias string) (string, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockURLService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockURLService_Expecter) GetURL(ctx interface{}, alias interface{}) *MockURLService_GetURL_Call {
	return &MockURLService_GetURL_Call{Call: _e.mock.On("GetURL", ctx, alias)}
}

func (_c *MockURLService_GetURL_Call) Run(run func(ctx context.Context, alias string)) *MockURLService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_GetURL_Call) Return(_a0 string, _a1 error) *MockURLService_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockURLService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function with given fields: ctx, userID
func (_m *MockURLService) GetUserURLs(ctx context.Context, userID uuid.UUID) ([]models.UserUrls, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []models.UserUrls
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserUrls, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserUrls); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserUrls)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockURLService_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockURLService_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *MockURLService_GetUserURLs_Call {
	return &MockURLService_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *MockURLService_GetUserURLs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockURLService_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockURLService_GetUserURLs_Call) Return(_a0 []models.UserUrls, _a1 error) *MockURLService_GetUserURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_GetUserURLs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserUrls, error)) *MockURLService_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
